name: Build IPA and Create Pull Request

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby for Cocoapods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies (Cocoapods)
        run: |
          gem install cocoapods
          pod install
        # Uncomment if you use Cocoapods

      # If you use fastlane to build IPA
      - name: Install Fastlane
        run: |
          gem install fastlane

      - name: Build IPA with Fastlane
        run: |
          fastlane gym --scheme "YourScheme" --export_method "ad-hoc"
        env:
          # Add secrets for code signing here
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa-artifact
          path: ./YourApp.ipa

      # Optionally, create a pull request for changes (e.g., if you are updating something)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Automated IPA build"
          body: "This PR is automatically created after building the IPA."
          branch: "auto/build-ipa"
